name: Rebase upstream

on:
  workflow_dispatch:
  schedule:
    - cron: "30 3 * * *"
      timezone: "Asia/Taipei"

permissions:
  contents: write

concurrency:
  group: rebase-upstream
  cancel-in-progress: false

jobs:
  sync:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          fetch-depth: 0
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Rebase upstream
        run: |
          set -e
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add upstream https://github.com/docker/github-builder.git
          git fetch upstream main
          git rebase upstream/main
          git push origin HEAD:main --force-with-lease
